// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD870FDeFVEYa41aiz-Xj1IjNfmqsONjsM',
    appId: '1:403219606060:web:11532ff65ab3347644bf89',
    messagingSenderId: '403219606060',
    projectId: 'food--n--go',
    authDomain: 'food--n--go.firebaseapp.com',
    storageBucket: 'food--n--go.firebasestorage.app',
    measurementId: 'G-S2K1TMYEQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN-gxY7LkO4Zi-wF9dWNDWyFIbgC-T-f0',
    appId: '1:403219606060:android:d2edf4504039ae3f44bf89',
    messagingSenderId: '403219606060',
    projectId: 'food--n--go',
    storageBucket: 'food--n--go.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaakcrwQS6vs7bTLkdU3vg2vX-KkLafkY',
    appId: '1:403219606060:ios:63f21cff3fbec1d444bf89',
    messagingSenderId: '403219606060',
    projectId: 'food--n--go',
    storageBucket: 'food--n--go.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaakcrwQS6vs7bTLkdU3vg2vX-KkLafkY',
    appId: '1:403219606060:ios:63f21cff3fbec1d444bf89',
    messagingSenderId: '403219606060',
    projectId: 'food--n--go',
    storageBucket: 'food--n--go.firebasestorage.app',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD870FDeFVEYa41aiz-Xj1IjNfmqsONjsM',
    appId: '1:403219606060:web:acdd470941a29c0c44bf89',
    messagingSenderId: '403219606060',
    projectId: 'food--n--go',
    authDomain: 'food--n--go.firebaseapp.com',
    storageBucket: 'food--n--go.firebasestorage.app',
    measurementId: 'G-K11EBD9ZSK',
  );

}